version: '3.8'
services:
  my-python-app:
    build:
      context: .         # relative path to the folder that has python.py & Dockerfile
      dockerfile: Dockerfile       # if it’s literally named “Dockerfile”
    image: my-python-app
    container_name: my-python-app
    restart: always
    ports:
      - "5000:5000"
    networks:
      - nginx-certbot

networks:
  nginx-certbot:
    external: true